# Generated by Django 3.2 on 2023-04-06 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
    ]
