# Generated by Django 3.2 on 2023-04-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_details',
            old_name='photo',
            new_name='product_photo1',
        ),
        migrations.AddField(
            model_name='product_details',
            name='product_photo2',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='product_details',
            name='product_photo3',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='product_details',
            name='product_photo4',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
