# Generated by Django 3.2 on 2024-06-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personalities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personFirstName', models.CharField(max_length=225)),
                ('personSecondName', models.CharField(max_length=225)),
                ('personPhoto', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('Photo1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('Photo2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('Photo3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('Photo4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
            ],
        ),
    ]
