# Generated by Django 3.2 on 2024-06-15 10:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('santhalMirror', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalities',
            name='description',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
