# Generated by Django 3.2 on 2024-06-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santhalMirror', '0002_personalities_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalities',
            name='sourceName',
            field=models.CharField(default='', max_length=225),
        ),
    ]
