# Generated by Django 3.2 on 2024-06-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santhalMirror', '0003_personalities_sourcename'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalities',
            name='SourcePhoto',
            field=models.ImageField(default='', upload_to='photos/%Y/%m/%d'),
        ),
    ]
