# Generated by Django 3.2 on 2023-04-02 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_team_google_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='google_link',
            new_name='github_link',
        ),
    ]
