# Generated by Django 3.2 on 2023-09-12 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_team_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='photo',
        ),
    ]
