# Generated by Django 3.2 on 2023-10-01 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_team_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='photo',
        ),
    ]
